
# Configuration racine
status = error
name = PropertiesConfig

# Configuration de l'appender Console
appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %x %-5p [%c{3}] [%t] %m%n

# Configuration du rootLogger
rootLogger.level = error
rootLogger.appenderRef.console.ref = Console

# Hibernate
logger.hibernate.name = org.hibernate
logger.hibernate.level = error

logger.hibernate-reporter.name = org.hibernate.util.JDBCExceptionReporter
logger.hibernate-reporter.level = fatal

logger.hibernate-event.name = org.hibernate.event.def.AbstractFlushingEventListener
logger.hibernate-event.level = fatal

logger.hibernate-type.name = org.hibernate.type
logger.hibernate-type.level = warn

logger.hibernate-settings.name = org.hibernate.cfg.SettingsFactory
logger.hibernate-settings.level = warn

# Spring
logger.spring.name = org.springframework
logger.spring.level = warn

logger.spring-remoting.name = org.springframework.remoting.support
logger.spring-remoting.level = error

logger.spring-util.name = org.springframework.util
logger.spring-util.level = error

# Axis/WSS4J
logger.axis.name = org.apache.axis
logger.axis.level = info

logger.ws.name = org.apache.ws
logger.ws.level = info

# CXF
logger.cxf.name = org.apache.cxf
logger.cxf.level = error

# Alfresco
logger.alfresco.name = org.alfresco
logger.alfresco.level = error

logger.alfresco-admin.name = org.alfresco.repo.admin
logger.alfresco-admin.level = info

logger.alfresco-transaction.name = org.alfresco.repo.transaction
logger.alfresco-transaction.level = warn

logger.alfresco-cache.name = org.alfresco.repo.cache.TransactionalCache
logger.alfresco-cache.level = warn

# CMIS
logger.opencmis.name = org.alfresco.opencmis
logger.opencmis.level = error

logger.cmis-interceptor.name = org.alfresco.opencmis.AlfrescoCmisServiceInterceptor
logger.cmis-interceptor.level = error

logger.cmis.name = org.alfresco.cmis
logger.cmis.level = error

# Web Framework
logger.webscripts.name = org.springframework.extensions.webscripts
logger.webscripts.level = info

logger.scriptlogger.name = org.springframework.extensions.webscripts.ScriptLogger
logger.scriptlogger.level = warn

# Collabora & Platform modules
logger.collabora-alfresco.name = fr.jeci.collabora.alfresco
logger.collabora-alfresco.level = debug

logger.collabora-wopi.name = fr.jeci.collabora.wopi
logger.collabora-wopi.level = debug
