# SPDX-FileCopyrightText: 2025 Jeci SARL - https://jeci.fr
#
# SPDX-License-Identifier: Apache-2.0

# Add here module-specific custom configuration
logger.jeci-collabora.name = fr.jeci.collabora
logger.jeci-collabora.level = warn

logger.jeci-collabora-job.name = fr.jeci.collabora.alfresco.job
logger.jeci-collabora-job.level = error
