worker_processes  auto;
error_log stderr;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
  worker_connections  1024;
}

http {
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

  # Don't tell nginx version to clients.
  server_tokens off;
  access_log /dev/stdout;

  sendfile            on;
  tcp_nopush          on;
  tcp_nodelay         on;
  keepalive_timeout   65;
  types_hash_max_size 2048;
  large_client_header_buffers 4 32k;

  include /etc/nginx/mime.types;
  default_type        application/octet-stream;

  # Set proxy cache config
  proxy_buffering on;
  proxy_cache_path  /var/cache/nginx   keys_zone=alfresco-cache:512m   inactive=5d;
  proxy_cache_key "$scheme$request_method$host$request_uri";

  server {
    listen ${public.port};
    server_name  ${public.host};
    charset utf-8;
    add_header Access-Control-Allow-Origin '';
    add_header Access-Control-Allow-Credentials 'true';

    client_max_body_size 1024m;

    # Semble necessaire poure Alfresco
    proxy_pass_request_headers on;
    proxy_pass_header Set-Cookie;

    location / {
      rewrite ^(.*) http://${public.host}:${public.port}/alfresco/;
    }

    location /alfresco/ {
      proxy_pass         http://alfresco:8080/alfresco/;
      proxy_redirect     default;

      include cors_support.conf;
      include proxy_pass.conf;
    }

    location = /share {
      rewrite ^ /share/ permanent;
    }

    location /share/ {
      proxy_pass         http://share:8080/share/;
      proxy_redirect     default;

      include cors_support.conf;
      include proxy_pass.conf;
    }

    location /api-explorer {
      proxy_pass         http://alfresco:8080/api-explorer;

      include proxy_pass.conf;
    }

		# static html, js, images, etc. served from loolwsd
		# loleaflet is the client part of LibreOffice Online
		location ~ ^/(loleaflet|browser)/.*$ {
			proxy_pass         http://collabora:9980;
			include proxy_pass.conf;
		}

		# WOPI discovery URL
		location ~ ^/hosting/(discovery|capabilities)$ {
			proxy_pass         http://collabora:9980;
			include proxy_pass.conf;
		}

		# Main websocket
		location ~ ^/(c|l)ool/(.*)/ws$ {
			proxy_pass         http://collabora:9980;
			include proxy_pass.conf;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			proxy_read_timeout 36000s;
		}

		# Download as, Fullscreen presentation and Image upload operations
		location ~ ^/(c|l)ool {
			proxy_pass         http://collabora:9980;
			include proxy_pass.conf;
		}

		# Admin Console websocket
		location ^~ /(adm|cool)/adminws {
			proxy_pass         http://collabora:9980;
			include proxy_pass.conf;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			proxy_read_timeout 36000s;
		}
  }
}
