---
version: '3.4'
services:
  ${acs.host}:
    image: collabora-platform-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-platform-extension-docker/target
    volumes:
      - content_services_volume:/usr/local/tomcat/alf_data
    depends_on:
      - ${db.host}
    networks:
      - backend

  ${share.host}:
    image: collabora-share-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-share-extension-docker/target
    environment:
      REPO_HOST: ${acs.host}
      REPO_PORT: 8080
    depends_on:
      - ${acs.host}
    networks:
      - backend


  ${appcontent.host}:
    image: collabora-aca-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-aca-extension-docker/target
    environment:
      BASE_PATH: ./
      PORT: 8080
      ACS_URL: http://${public.host}:${public.port}

      URL_HOST_ADF: http://${public.host}:8080/alfresco
      APP_BASE_SHARE_URL: http://${public.host}:8080/share/s
      PROXY_HOST_ADF: http://${public.host}:8080/demo
      URL_HOST_BPM_ADF: http://${public.host}:8080
      NOTIFICATION_LAST: 2000
      AUTH_TYPE: BASIC
      PROVIDERS: ALL
    ports:
      - "${public.port}:8080"
    depends_on:
      - ${acs.host}
    networks:
      - backend


  ${db.host}:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - backend

  ${solr.host}:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: ${acs.host}
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ${solr.host}
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    volumes:
      - solr_contentstore_volume:/opt/alfresco-search-services/contentstore
      - solr_data_volume:/opt/alfresco-search-services/data
    networks:
      - backend

  ${code.host}:
    image: ${docker.code.image}:${docker.code.version}
    privileged: true
    environment:
      extra_params: '--o:ssl.enable=false --o:server_name=${public.host}:9980'
    ports:
    - "9980:9980"
    networks:
      - backend

volumes:
  content_services_volume:
  db_volume:
  solr_contentstore_volume:
  solr_data_volume:

networks:
  backend:
