---
version: '3.4'
services:
  ${acs.host}:
    image: collabora-platform-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-platform-extension-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dmessaging.broker.url=\"failover:(nio://${activemq.host}:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    volumes:
      - ${acs.host}-volume:/usr/local/tomcat/alf_data
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    depends_on:
      - ${db.host}
    networks:
      - backend

  ${share.host}:
    image: collabora-share-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-share-extension-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: ${acs.host}
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${appcontent.host}:
    image: collabora-aca-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-aca-extension-docker/target
    environment:
      BASE_PATH: ./
      PORT: 8080
      ACS_URL: http://${public.host}:${appcontent.port}

      URL_HOST_ADF: http://${public.host}:8080/alfresco
      APP_BASE_SHARE_URL: http://${public.host}:8080/share/s
      PROXY_HOST_ADF: http://${public.host}:8080/demo
      URL_HOST_BPM_ADF: http://${public.host}:8080
      NOTIFICATION_LAST: 2000
      AUTH_TYPE: BASIC
      PROVIDERS: ALL
    ports:
      - "${appcontent.port}:8080"
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${activemq.host}:
    image: ${docker.activemq.image}:${docker.activemq.version}
    mem_limit: 1g
    depends_on:
      - ${acs.host}
    ports:
      - ${activemq.console.port}:8161 # Web Console
      - ${activemq.amqp.port}:5672 # AMQP
      - ${activemq.openwire.port}:61616 # OpenWire
      - ${activemq.stomp.port}:61613 # STOMP
    networks:
      - backend

  ${db.host}:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - ${db.host}-volume:/var/lib/postgresql/data
    ports:
      - "${db.port}:5432"
    networks:
      - backend


  ${solr.host}:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: ${acs.host}
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ${solr.host}
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    volumes:
      - ${solr.host}-volume:/opt/alfresco-search-services/contentstore
      - ${solr.host}-volume:/opt/alfresco-search-services/data
    ports:
      - "${solr.port}:8983"
    networks:
      - backend

  ${code.host}:
    image: ${docker.code.image}:${docker.code.version}
    privileged: true
    environment:
      extra_params: '--o:ssl.enable=false --o:server_name=${public.host}:9980'
    ports:
    - "${code.port}:9980"
    networks:
      - backend

networks:
  backend:

volumes:
  ${acs.host}-volume:
  ${db.host}-volume:
  ${solr.host}-volume:
