---
services:
  alfresco:
    image: collabora-platform-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-platform-extension-docker/target
    environment:
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
    volumes:
      - alfresco-volume:/usr/local/tomcat/alf_data
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - backend

  share:
    image: collabora-share-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-share-extension-docker/target
    environment:
      REPO_HOST: alfresco
      REPO_PORT: 8080
      CSRF_FILTER_REFERER: "http://${public.host}:${public.port}/.*"
      CSRF_FILTER_ORIGIN: "http://${public.host}:${public.port}"
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8001,server=y,suspend=n"
    depends_on:
      - alfresco
    ports:
      - "8001:8001"
    networks:
      - backend

  postgres:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - backend

  solr6:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: alfresco
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    volumes:
      - solr6-contentstore-volume:/opt/alfresco-search-services/contentstore
      - solr6-data-volume:/opt/alfresco-search-services/data
      - solr6-keystores-volume:/opt/alfresco-search-services/keystores
      - solr6-solrhome-volume:/opt/alfresco-search-services/solrhome
    depends_on:
      - alfresco
    networks:
      - backend

  alfresco-collabora-online:
    image: alfresco-collabora-online:development
    build:
      dockerfile: ./Dockerfile
      context: ../../alfresco-collabora-online-docker/target
    environment:
      PORT: 8080
      PROXY_HOST: http://${public.host}:${public.port}
    ports:
      - ${public.port}:8080
    depends_on:
      - alfresco
      - share
    networks:
      - backend

  collabora:
    image: ${docker.code.image}:${docker.code.version}
    privileged: true
    environment:
      extra_params: '--o:ssl.enable=false --o:server_name=${public.host}:9980'
    ports:
      - "9980:9980"
    networks:
      - backend

volumes:
  alfresco-volume:
  postgres-volume:
  solr6-contentstore-volume:
  solr6-data-volume:
  solr6-keystores-volume:
  solr6-solrhome-volume:

networks:
  backend:

