---
version: '3.4'
services:
  ${acs.host}:
    image: collabora-platform-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-platform-extension-docker/target
    environment:
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
    volumes:
      - ${acs.host}-volume:/usr/local/tomcat/alf_data
    depends_on:
      - ${db.host}
    ports:
      - "8000:8000"
    networks:
      - backend

  ${share.host}:
    image: collabora-share-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-share-extension-docker/target
    environment:
      REPO_HOST: ${acs.host}
      REPO_PORT: 8080
      CSRF_FILTER_REFERER: "http://${public.host}:${public.port}/.*"
      CSRF_FILTER_ORIGIN: "http://${public.host}:${public.port}"
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8001,server=y,suspend=n"
    depends_on:
      - ${acs.host}
    ports:
      - "8001:8001"
    networks:
      - backend

  ${db.host}:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - ${db.host}-volume:/var/lib/postgresql/data
    networks:
      - backend

  ${solr.host}:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: ${acs.host}
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ${solr.host}
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    volumes:
      - ${solr.host}-contentstore-volume:/opt/alfresco-search-services/contentstore
      - ${solr.host}-data-volume:/opt/alfresco-search-services/data
      - ${solr.host}-keystores-volume:/opt/alfresco-search-services/keystores
      - ${solr.host}-solrhome-volume:/opt/alfresco-search-services/solrhome
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${activemq.host}:
    image: ${docker.activemq.image}:${docker.activemq.version}
    depends_on:
      - ${acs.host}
    volumes:
      - ${activemq.host}-activemq-volume:/opt/activemq/conf
    networks:
      - backend

  ${transform-core-aio.host}:
    image: ${docker.transform-core-aio.image}:${docker.transform-core-aio.version}
    depends_on:
      - ${acs.host}
      - ${activemq.host}
    networks:
      - backend

  ${appcontent.host}:
    image: collabora-aca-extension:development
    build:
      dockerfile: ./Dockerfile
      context: ../../collabora-aca-extension-docker/target
    environment:
      BASE_PATH: ./
      PORT: 8080
      ACS_URL: http://${public.host}:${public.port}

      URL_HOST_ADF: http://${public.host}:${public.port}/alfresco
      APP_BASE_SHARE_URL: http://${public.host}:${public.port}/share/s
      PROXY_HOST_ADF: http://${public.host}:${public.port}/demo
      URL_HOST_BPM_ADF: http://${public.host}:${public.port}
      NOTIFICATION_LAST: 2000
      AUTH_TYPE: BASIC
      PROVIDERS: ALL
    ports:
      - "${public.port}:8080"
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${code.host}:
    image: ${docker.code.image}:${docker.code.version}
    privileged: true
    environment:
      extra_params: '--o:ssl.enable=false --o:server_name=${public.host}:9980'
    ports:
      - "${code.port}:9980"
    networks:
      - backend

volumes:
  ${acs.host}-volume:
  ${db.host}-volume:
  ${solr.host}-contentstore-volume:
  ${solr.host}-data-volume:
  ${solr.host}-keystores-volume:
  ${solr.host}-solrhome-volume:
  ${activemq.host}-activemq-volume:

networks:
  backend:

