# SPDX-FileCopyrightText: 2025 Jeci SARL - https://jeci.fr
#
# SPDX-License-Identifier: Apache-2.0

page.collabora-online-edit.title=Redigerer med Collabora Online
aspect.collabora_collaboraOnline=Collabora Online
details.banner.collabora-editing=Redigeres nå med Collabora Online
status.collabora-editing=Redigerer med Collabora Online
actions.document.edit-collabora-online=Rediger med Collabora Online
