# SPDX-FileCopyrightText: 2025 Jeci SARL - https://jeci.fr
#
# SPDX-License-Identifier: Apache-2.0

page.collabora-online-edit.title=Editing with Collabora Online
aspect.collabora_collaboraOnline=Collabora Online
details.banner.collabora-editing=Currently edited with Collabora Online
status.collabora-editing=Editing with Collabora Online
actions.document.edit-collabora-online=Edit in Collabora Online
