# Configuration racine
status = error
name = PropertiesConfig

# Configuration de l'appender Console
appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %x %-5p [%c{3}] [%t] %m%n

# Configuration du rootLogger
rootLogger.level = error
rootLogger.appenderRef.console.ref = Console

# Configuration des loggers spécifiques
# Spring
logger.spring.name = org.springframework
logger.spring.level = warn

logger.spring-remoting.name = org.springframework.remoting.support
logger.spring-remoting.level = error

logger.spring-util.name = org.springframework.util
logger.spring-util.level = error

# MyFaces
logger.myfaces-debug.name = org.apache.myfaces.util.DebugUtils
logger.myfaces-debug.level = info

logger.myfaces-resolver.name = org.apache.myfaces.el.VariableResolverImpl
logger.myfaces-resolver.level = error

logger.myfaces-jsp.name = org.apache.myfaces.application.jsp.JspViewHandlerImpl
logger.myfaces-jsp.level = error

logger.myfaces-taglib.name = org.apache.myfaces.taglib
logger.myfaces-taglib.level = error

# Alfresco
logger.alfresco.name = org.alfresco
logger.alfresco.level = error

logger.alfresco-config.name = org.alfresco.config
logger.alfresco-config.level = warn

logger.alfresco-jndi.name = org.alfresco.config.JndiObjectFactoryBean
logger.alfresco-jndi.level = warn

logger.alfresco-web.name = org.alfresco.web
logger.alfresco-web.level = info

# Web Framework
logger.webscripts.name = org.springframework.extensions.webscripts
logger.webscripts.level = info

logger.scriptlogger.name = org.springframework.extensions.webscripts.ScriptLogger
logger.scriptlogger.level = warn

logger.scriptdebugger.name = org.springframework.extensions.webscripts.ScriptDebugger
logger.scriptdebugger.level = off

# Freemarker
logger.freemarker.name = freemarker.runtime
logger.freemarker.level = error

# Collabora
logger.collabora.name = fr.jeci.collabora.evaluator.doclib.indicator
logger.collabora.level = debug

# Old Lib Reference
logger.libreoffice.name = dk.magenta.libreOffice.online
logger.libreoffice.level = debug
